- name: Update 'pacman' cache
  pacman:
    update_cache: true

- name: Get /etc/ssl/certs/ca-certificates.crt hash
  stat:
    path: /etc/ssl/certs/ca-certificates.crt
  register: ca_certificates_stat
  when: upgrade_delete

- name: Delete outdated ca-certificates file before upgrade
  file:
    path: /etc/ssl/certs/ca-certificates.crt
    state: absent
  when: upgrade_delete and ca_certificates_stat.stat.checksum is defined and ca_certificates_stat.stat.checksum == "{{ upgrade_delete_checksum }}"

- name: Update Arch Linux via 'pacman'
  pacman:
    upgrade: yes
  when: upgrade_run_upgrade

- name: Update AUR packages via 'pacaur'
  command: pacaur -Syuq --noconfirm
  when: upgrade_run_upgrade
